//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.14 at 02:34:33 PM MSK 
//


package com.Substation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.Substation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Substation_QNAME = new QName("http://www.iec.ch/61850/2006/SCL", "Substation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.Substation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link THeader }
     * 
     */
    public THeader createTHeader() {
        return new THeader();
    }

    /**
     * Create an instance of {@link TSubstation }
     * 
     */
    public TSubstation createTSubstation() {
        return new TSubstation();
    }

    /**
     * Create an instance of {@link TBitRateInMbPerSec }
     * 
     */
    public TBitRateInMbPerSec createTBitRateInMbPerSec() {
        return new TBitRateInMbPerSec();
    }

    /**
     * Create an instance of {@link TConductingEquipment }
     * 
     */
    public TConductingEquipment createTConductingEquipment() {
        return new TConductingEquipment();
    }

    /**
     * Create an instance of {@link TBay }
     * 
     */
    public TBay createTBay() {
        return new TBay();
    }

    /**
     * Create an instance of {@link TSubFunction }
     * 
     */
    public TSubFunction createTSubFunction() {
        return new TSubFunction();
    }

    /**
     * Create an instance of {@link TVoltage }
     * 
     */
    public TVoltage createTVoltage() {
        return new TVoltage();
    }

    /**
     * Create an instance of {@link TPowerTransformer }
     * 
     */
    public TPowerTransformer createTPowerTransformer() {
        return new TPowerTransformer();
    }

    /**
     * Create an instance of {@link TVoltageLevel }
     * 
     */
    public TVoltageLevel createTVoltageLevel() {
        return new TVoltageLevel();
    }

    /**
     * Create an instance of {@link TVal }
     * 
     */
    public TVal createTVal() {
        return new TVal();
    }

    /**
     * Create an instance of {@link TLNode }
     * 
     */
    public TLNode createTLNode() {
        return new TLNode();
    }

    /**
     * Create an instance of {@link TTransformerWinding }
     * 
     */
    public TTransformerWinding createTTransformerWinding() {
        return new TTransformerWinding();
    }

    /**
     * Create an instance of {@link TValueWithUnit }
     * 
     */
    public TValueWithUnit createTValueWithUnit() {
        return new TValueWithUnit();
    }

    /**
     * Create an instance of {@link TFunction }
     * 
     */
    public TFunction createTFunction() {
        return new TFunction();
    }

    /**
     * Create an instance of {@link TText }
     * 
     */
    public TText createTText() {
        return new TText();
    }

    /**
     * Create an instance of {@link TGeneralEquipment }
     * 
     */
    public TGeneralEquipment createTGeneralEquipment() {
        return new TGeneralEquipment();
    }

    /**
     * Create an instance of {@link TConnectivityNode }
     * 
     */
    public TConnectivityNode createTConnectivityNode() {
        return new TConnectivityNode();
    }

    /**
     * Create an instance of {@link TTapChanger }
     * 
     */
    public TTapChanger createTTapChanger() {
        return new TTapChanger();
    }

    /**
     * Create an instance of {@link TDurationInSec }
     * 
     */
    public TDurationInSec createTDurationInSec() {
        return new TDurationInSec();
    }

    /**
     * Create an instance of {@link TTerminal }
     * 
     */
    public TTerminal createTTerminal() {
        return new TTerminal();
    }

    /**
     * Create an instance of {@link TPrivate }
     * 
     */
    public TPrivate createTPrivate() {
        return new TPrivate();
    }

    /**
     * Create an instance of {@link TDurationInMilliSec }
     * 
     */
    public TDurationInMilliSec createTDurationInMilliSec() {
        return new TDurationInMilliSec();
    }

    /**
     * Create an instance of {@link TSubEquipment }
     * 
     */
    public TSubEquipment createTSubEquipment() {
        return new TSubEquipment();
    }

    /**
     * Create an instance of {@link THitem }
     * 
     */
    public THitem createTHitem() {
        return new THitem();
    }

    /**
     * Create an instance of {@link THeader.History }
     * 
     */
    public THeader.History createTHeaderHistory() {
        return new THeader.History();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSubstation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iec.ch/61850/2006/SCL", name = "Substation")
    public JAXBElement<TSubstation> createSubstation(TSubstation value) {
        return new JAXBElement<TSubstation>(_Substation_QNAME, TSubstation.class, null, value);
    }

}
