<?xml version="1.0" encoding="UTF-8"?>
<SCL xmlns:sxy="http://www.iec.ch/61850/2003/SCLcoordinates" version="2007" revision="B" xmlns="http://www.iec.ch/61850/2003/SCL">
  <Header id="project2" version="1" revision="1" toolID="SCL Manager" nameStructure="IEDName" />
  <Substation name="substation1" sxy:x="0" sxy:y="0">
    <PowerTransformer name="AT1" type="PTR" sxy:x="12" sxy:y="27">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode115" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode115" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode35" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode35" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay10/connvtyNode31" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay10" cNodeName="connvtyNode31" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="AT2" type="PTR" sxy:x="5" sxy:y="25">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode69" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode69" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode41" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode41" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay12/connvtyNode33" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay12" cNodeName="connvtyNode33" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="AT3" type="PTR" sxy:x="16" sxy:y="28">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode102" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode102" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode37" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode37" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay11/connvtyNode32" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay11" cNodeName="connvtyNode32" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="AT4" type="PTR" sxy:x="19" sxy:y="26">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode64" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode64" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode43" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode43" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay13/connvtyNode34" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay13" cNodeName="connvtyNode34" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="T2" type="PTR" sxy:x="31" sxy:y="24">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay2/connvtyNode139" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay2" cNodeName="connvtyNode139" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay3/connvtyNode141" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay3" cNodeName="connvtyNode141" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode53" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode53" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="T4" type="PTR" sxy:x="71" sxy:y="23">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode123" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode123" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="T3" type="PTR" sxy:x="79" sxy:y="24">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode134" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode134" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="AT5" type="PTR" sxy:x="43" sxy:y="26">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode77" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode77" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="T1" type="PTR" sxy:x="50" sxy:y="26">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay1/connvtyNode137" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay1" cNodeName="connvtyNode137" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode88" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode88" />
      </TransformerWinding>
    </PowerTransformer>
	<PowerTransformer name="AT6" type="PTR" sxy:x="65" sxy:y="23">
      <TransformerWinding name="transfmrWndg1" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg2" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/null/null/null" substationName="substation1" voltageLevelName="null" bayName="null" cNodeName="null" />
      </TransformerWinding>
      <TransformerWinding name="transfmrWndg3" type="PTW">
        <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode110" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode110" />
      </TransformerWinding>
    </PowerTransformer>
	<VoltageLevel name="voltageLevel1" sxy:x="0" sxy:y="0">
      <Voltage unit="V">500</Voltage>
      <Bay name="bay1" sxy:x="1" sxy:y="5">
        <ConductingEquipment name="W1CQS1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay2/connvtyNode9" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay2" cNodeName="connvtyNode9" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode1" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode1" />
        </ConductingEquipment>
		<ConductingEquipment name="W1CQ1" type="CBR" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode1" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode1" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode2" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode2" />
        </ConductingEquipment>
		<ConductingEquipment name="W1CQS2" type="DIS" sxy:x="1" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode2" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode2" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode3" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode3" />
        </ConductingEquipment>
		<ConductingEquipment name="W1W5CQS1" type="DIS" sxy:x="1" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode3" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode3" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode4" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode4" />
        </ConductingEquipment>
		<ConductingEquipment name="W1W5CQX1" type="CBR" sxy:x="1" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode4" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode4" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode5" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode5" />
        </ConductingEquipment>
		<ConductingEquipment name="W1W5CQS2" type="DIS" sxy:x="1" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode5" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode5" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode6" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode6" />
        </ConductingEquipment>
		<ConductingEquipment name="W5CQS2" type="DIS" sxy:x="1" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode6" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode6" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode7" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode7" />
        </ConductingEquipment>
		<ConductingEquipment name="W5CQ2" type="CBR" sxy:x="1" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode7" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode7" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode8" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode8" />
        </ConductingEquipment>
		<ConductingEquipment name="W5CQS1" type="DIS" sxy:x="1" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode8" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode8" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay3/connvtyNode10" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay3" cNodeName="connvtyNode10" />
        </ConductingEquipment>
		<ConductingEquipment name="W1CQSG12" type="DIS" sxy:x="2" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay2/connvtyNode9" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay2" cNodeName="connvtyNode9" />
        </ConductingEquipment>
		<ConductingEquipment name="W1CQSG11" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode1" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode1" />
        </ConductingEquipment>
		<ConductingEquipment name="W1CQSG21" type="DIS" sxy:x="2" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode2" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode2" />
        </ConductingEquipment>
		<ConductingEquipment name="W1CQSG22" type="DIS" sxy:x="2" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode3" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode3" />
        </ConductingEquipment>
		<ConductingEquipment name="W1W5CQSG1" type="DIS" sxy:x="2" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode4" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode4" />
        </ConductingEquipment>
		<ConductingEquipment name="W1W5CQSG21" type="DIS" sxy:x="1" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode5" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode5" />
        </ConductingEquipment>
		<ConductingEquipment name="W1W5CQSG22" type="DIS" sxy:x="1" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode6" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode6" />
        </ConductingEquipment>
		<ConductingEquipment name="W5CQSG2" type="DIS" sxy:x="1" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode7" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode7" />
        </ConductingEquipment>
		<ConductingEquipment name="W5CQSG11" type="DIS" sxy:x="1" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode8" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode8" />
        </ConductingEquipment>
		<ConductingEquipment name="W5CQSG12" type="DIS" sxy:x="1" sxy:y="16">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay3/connvtyNode10" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay3" cNodeName="connvtyNode10" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode1" pathName="substation1/voltageLevel1/bay1/connvtyNode1" sxy:x="1" sxy:y="2" />
		<ConnectivityNode name="connvtyNode2" pathName="substation1/voltageLevel1/bay1/connvtyNode2" sxy:x="1" sxy:y="4" />
		<ConnectivityNode name="connvtyNode3" pathName="substation1/voltageLevel1/bay1/connvtyNode3" sxy:x="0" sxy:y="6" />
		<ConnectivityNode name="connvtyNode4" pathName="substation1/voltageLevel1/bay1/connvtyNode4" sxy:x="1" sxy:y="8" />
		<ConnectivityNode name="connvtyNode5" pathName="substation1/voltageLevel1/bay1/connvtyNode5" sxy:x="1" sxy:y="10" />
		<ConnectivityNode name="connvtyNode6" pathName="substation1/voltageLevel1/bay1/connvtyNode6" sxy:x="0" sxy:y="12" />
		<ConnectivityNode name="connvtyNode7" pathName="substation1/voltageLevel1/bay1/connvtyNode7" sxy:x="1" sxy:y="13" />
		<ConnectivityNode name="connvtyNode8" pathName="substation1/voltageLevel1/bay1/connvtyNode8" sxy:x="1" sxy:y="15" />
      </Bay>
	  <Bay name="bay2" sxy:x="1" sxy:y="3">
        <ConnectivityNode name="connvtyNode9" pathName="substation1/voltageLevel1/bay2/connvtyNode9" sxy:x="1" sxy:y="0" />
      </Bay>
	  <Bay name="bay3" sxy:x="1" sxy:y="21">
        <ConnectivityNode name="connvtyNode10" pathName="substation1/voltageLevel1/bay3/connvtyNode10" sxy:x="1" sxy:y="0" />
      </Bay>
	  <Bay name="bay5" sxy:x="4" sxy:y="0">
		<ConductingEquipment name="W1Cрезерв" type="IFL" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay5/connvtyNode11" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay5" cNodeName="connvtyNode11" />
        </ConductingEquipment>
		<ConductingEquipment name="W1CQSG3" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay5/connvtyNode11" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay5" cNodeName="connvtyNode11" />
        </ConductingEquipment>
		<ConductingEquipment name="W1CQS3" type="DIS" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay5/connvtyNode11" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay5" cNodeName="connvtyNode11" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode3" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode3" />
        </ConductingEquipment>		
        <ConnectivityNode name="connvtyNode11" pathName="substation1/voltageLevel1/bay5/connvtyNode11" sxy:x="1" sxy:y="1" />
      </Bay>
	  <Bay name="bay4" sxy:x="7" sxy:y="0">
		<ConductingEquipment name="W5C" type="IFL" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay4/connvtyNode12" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay4" cNodeName="connvtyNode12" />
        </ConductingEquipment>
		<ConductingEquipment name="W5CQSG3" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay4/connvtyNode12" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay4" cNodeName="connvtyNode12" />
        </ConductingEquipment>
		<ConductingEquipment name="W5CQS3" type="DIS" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay4/connvtyNode12" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay4" cNodeName="connvtyNode12" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay1/connvtyNode6" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay1" cNodeName="connvtyNode6" />
        </ConductingEquipment>		
        <ConnectivityNode name="connvtyNode12" pathName="substation1/voltageLevel1/bay4/connvtyNode12" sxy:x="1" sxy:y="1" />
      </Bay>
	  <Bay name="bay6" sxy:x="10" sxy:y="4">
		<ConductingEquipment name="AT1CQS1" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay2/connvtyNode9" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay2" cNodeName="connvtyNode9" />
          <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode13" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode13" />		  
        </ConductingEquipment>
		<ConductingEquipment name="AT1CQ1" type="CBR" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode13" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode13" />
          <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode14" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode14" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1CQS2" type="DIS" sxy:x="2" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode14" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode14" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode15" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode15" />
        </ConductingEquipment>		
		<ConductingEquipment name="W3AT1CQS1" type="DIS" sxy:x="2" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode15" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode15" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode16" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode16" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1CQZ1" type="CBR" sxy:x="2" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode16" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode16" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode17" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode17" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1CQS2" type="DIS" sxy:x="2" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode17" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode17" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode18" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode18" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQS2" type="DIS" sxy:x="2" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode18" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode18" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode19" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode19" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQ2" type="CBR" sxy:x="2" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode19" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode19" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode20" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode20" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQS1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode20" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode20" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay3/connvtyNode10" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay3" cNodeName="connvtyNode10" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1CQSG1" type="DIS" sxy:x="3" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode13" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode13" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1CQSG2" type="DIS" sxy:x="3" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode14" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode14" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1CQSG11" type="DIS" sxy:x="3" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode16" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode16" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1CQSG2" type="DIS" sxy:x="3" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode17" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode17" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQSG22" type="DIS" sxy:x="3" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode18" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode18" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQSG21" type="DIS" sxy:x="3" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode19" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode19" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQSG11" type="DIS" sxy:x="3" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode20" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode20" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQSG12" type="DIS" sxy:x="3" sxy:y="16">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay3/connvtyNode10" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay3" cNodeName="connvtyNode10" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1CQSG12" type="DIS" sxy:x="3" sxy:y="6">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode15" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode15" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode13" pathName="substation1/voltageLevel1/bay6/connvtyNode13" sxy:x="2" sxy:y="2" />
		<ConnectivityNode name="connvtyNode14" pathName="substation1/voltageLevel1/bay6/connvtyNode14" sxy:x="2" sxy:y="4" />
		<ConnectivityNode name="connvtyNode15" pathName="substation1/voltageLevel1/bay6/connvtyNode15" sxy:x="0" sxy:y="6" />
		<ConnectivityNode name="connvtyNode16" pathName="substation1/voltageLevel1/bay6/connvtyNode16" sxy:x="2" sxy:y="8" />
		<ConnectivityNode name="connvtyNode17" pathName="substation1/voltageLevel1/bay6/connvtyNode17" sxy:x="2" sxy:y="10" />
		<ConnectivityNode name="connvtyNode18" pathName="substation1/voltageLevel1/bay6/connvtyNode18" sxy:x="1" sxy:y="12" />
		<ConnectivityNode name="connvtyNode19" pathName="substation1/voltageLevel1/bay6/connvtyNode19" sxy:x="2" sxy:y="13" />
		<ConnectivityNode name="connvtyNode20" pathName="substation1/voltageLevel1/bay6/connvtyNode20" sxy:x="2" sxy:y="15" />
      </Bay>
	  <Bay name="bay7" sxy:x="13" sxy:y="0">
		<ConductingEquipment name="W3C" type="IFL" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay7/connvtyNode21" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay7" cNodeName="connvtyNode21" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQSG3" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay7/connvtyNode21" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay7" cNodeName="connvtyNode21" />
        </ConductingEquipment>
		<ConductingEquipment name="W3CQS3" type="DIS" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay7/connvtyNode21" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay7" cNodeName="connvtyNode21" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode18" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode18" />
        </ConductingEquipment>		
        <ConnectivityNode name="connvtyNode21" pathName="substation1/voltageLevel1/bay7/connvtyNode21" sxy:x="1" sxy:y="1" />
      </Bay>
      <Bay name="bay8" sxy:x="18" sxy:y="4">
        <ConductingEquipment name="W4CQS1" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay2/connvtyNode9" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay2" cNodeName="connvtyNode9" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode1" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode1" />
        </ConductingEquipment>
		<ConductingEquipment name="W4CQ1" type="CBR" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode22" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode22" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode23" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode23" />
        </ConductingEquipment>
		<ConductingEquipment name="W4CQS2" type="DIS" sxy:x="2" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode23" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode23" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode24" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode24" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT4CQS1" type="DIS" sxy:x="2" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode24" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode24" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode25" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode25" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT4CQZ1" type="CBR" sxy:x="2" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode25" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode25" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode26" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode26" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT4CQS2" type="DIS" sxy:x="2" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode26" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode26" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode27" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode27" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4CQS2" type="DIS" sxy:x="2" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode27" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode27" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode28" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode28" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4CQ2" type="CBR" sxy:x="2" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode28" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode28" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode29" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode29" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4CQS1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode29" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode29" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay3/connvtyNode10" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay3" cNodeName="connvtyNode10" />
        </ConductingEquipment>
		<ConductingEquipment name="W4CQSG11" type="DIS" sxy:x="3" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode22" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode22" />
        </ConductingEquipment>
		<ConductingEquipment name="W4CQSG21" type="DIS" sxy:x="3" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode23" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode23" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT4CQSG1" type="DIS" sxy:x="3" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode25" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode25" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT4CQSG21" type="DIS" sxy:x="3" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode26" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode26" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT4CQSG22" type="DIS" sxy:x="3" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode27" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode27" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4CQSG2" type="DIS" sxy:x="3" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode28" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode28" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4CQSG1" type="DIS" sxy:x="3" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode29" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode29" />
        </ConductingEquipment>
		<ConductingEquipment name="W4CQSG22" type="DIS" sxy:x="3" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode24" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode24" />
        </ConductingEquipment>
		<ConductingEquipment name="W4CQSG12" type="DIS" sxy:x="3" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay2/connvtyNode9" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay2" cNodeName="connvtyNode9" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode22" pathName="substation1/voltageLevel1/bay8/connvtyNode22" sxy:x="2" sxy:y="2" />
		<ConnectivityNode name="connvtyNode23" pathName="substation1/voltageLevel1/bay8/connvtyNode23" sxy:x="2" sxy:y="4" />
		<ConnectivityNode name="connvtyNode24" pathName="substation1/voltageLevel1/bay8/connvtyNode24" sxy:x="1" sxy:y="5" />
		<ConnectivityNode name="connvtyNode25" pathName="substation1/voltageLevel1/bay8/connvtyNode25" sxy:x="2" sxy:y="8" />
		<ConnectivityNode name="connvtyNode26" pathName="substation1/voltageLevel1/bay8/connvtyNode26" sxy:x="2" sxy:y="10" />
		<ConnectivityNode name="connvtyNode27" pathName="substation1/voltageLevel1/bay8/connvtyNode27" sxy:x="0" sxy:y="11" />
		<ConnectivityNode name="connvtyNode28" pathName="substation1/voltageLevel1/bay8/connvtyNode28" sxy:x="2" sxy:y="13" />
		<ConnectivityNode name="connvtyNode29" pathName="substation1/voltageLevel1/bay8/connvtyNode29" sxy:x="2" sxy:y="15" />
      </Bay>
	  <Bay name="bay9" sxy:x="21" sxy:y="0">
		<ConductingEquipment name="W4C" type="IFL" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay9/connvtyNode30" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay9" cNodeName="connvtyNode30" />
        </ConductingEquipment>
		<ConductingEquipment name="W4CQSG3" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay9/connvtyNode30" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay9" cNodeName="connvtyNode30" />
        </ConductingEquipment>
		<ConductingEquipment name="W4CQS3" type="DIS" sxy:x="1" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay9/connvtyNode30" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay9" cNodeName="connvtyNode30" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode24" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode24" />
        </ConductingEquipment>		
        <ConnectivityNode name="connvtyNode30" pathName="substation1/voltageLevel1/bay9/connvtyNode30" sxy:x="1" sxy:y="1" />
      </Bay>
	  <Bay name="bay10" sxy:x="9" sxy:y="22">
		<ConductingEquipment name="AT1CQSG3" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay10/connvtyNode31" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay10" cNodeName="connvtyNode31" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1CQS3" type="DIS" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay6/connvtyNode15" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay6" cNodeName="connvtyNode15" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay10/connvtyNode31" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay10" cNodeName="connvtyNode31" />
        </ConductingEquipment>		
        <ConnectivityNode name="connvtyNode31" pathName="substation1/voltageLevel1/bay10/connvtyNode31" sxy:x="1" sxy:y="1" />
      </Bay>
	  <Bay name="bay11" sxy:x="15" sxy:y="22">
		<ConductingEquipment name="AT3CQSG3" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay11/connvtyNode32" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay11" cNodeName="connvtyNode32" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3CQS3" type="DIS" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay2/connvtyNode9" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay2" cNodeName="connvtyNode9" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay11/connvtyNode32" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay11" cNodeName="connvtyNode32" />
        </ConductingEquipment>		
        <ConnectivityNode name="connvtyNode32" pathName="substation1/voltageLevel1/bay11/connvtyNode32" sxy:x="1" sxy:y="1" />
      </Bay>
	  <Bay name="bay12" sxy:x="4" sxy:y="22">
		<ConductingEquipment name="AT2CQSG1" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay12/connvtyNode33" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay12" cNodeName="connvtyNode33" />
        </ConductingEquipment>
		<ConductingEquipment name="AT2CQS1" type="DIS" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay3/connvtyNode10" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay3" cNodeName="connvtyNode10" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay12/connvtyNode33" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay12" cNodeName="connvtyNode33" />
        </ConductingEquipment>		
        <ConnectivityNode name="connvtyNode33" pathName="substation1/voltageLevel1/bay12/connvtyNode33" sxy:x="1" sxy:y="1" />
      </Bay>
	  <Bay name="bay13" sxy:x="18" sxy:y="22">
		<ConductingEquipment name="AT4CQSG3" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay13/connvtyNode34" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay13" cNodeName="connvtyNode34" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4CQS3" type="DIS" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel1/bay8/connvtyNode27" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay8" cNodeName="connvtyNode27" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel1/bay13/connvtyNode34" substationName="substation1" voltageLevelName="voltageLevel1" bayName="bay13" cNodeName="connvtyNode34" />
        </ConductingEquipment>		
        <ConnectivityNode name="connvtyNode34" pathName="substation1/voltageLevel1/bay13/connvtyNode34" sxy:x="1" sxy:y="1" />
      </Bay>
    </VoltageLevel>
	<VoltageLevel name="voltageLevel3" sxy:x="0" sxy:y="29">
      <Voltage unit="V">20</Voltage>
      <Bay name="bay14" sxy:x="10" sxy:y="1">
		<ConductingEquipment name="AT1SQSG22" type="DIS" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode36" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode36" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1SQS2" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode35" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode35" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode36" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode36" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1SQSG21" type="DIS" sxy:x="2" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode35" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode35" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3SQSG11" type="DIS" sxy:x="6" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode37" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode37" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3SQS1" type="DIS" sxy:x="5" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode37" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode37" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode36" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode36" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3SQSG12" type="DIS" sxy:x="6" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode36" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode36" />
        </ConductingEquipment>
		<ConductingEquipment name="GS1QSG2" type="DIS" sxy:x="4" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode36" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode36" />
        </ConductingEquipment>
		<ConductingEquipment name="GS1QS2" type="DIS" sxy:x="3" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode36" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode36" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode38" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode38" />
        </ConductingEquipment>
		<ConductingEquipment name="GS1Q2" type="CBR" sxy:x="3" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode38" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode38" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode39" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode39" />
        </ConductingEquipment>
		<ConductingEquipment name="GS1QSG1" type="DIS" sxy:x="4" sxy:y="6">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode39" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode39" />
        </ConductingEquipment>
		<ConductingEquipment name="GS1QS1" type="DIS" sxy:x="3" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode39" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode39" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode40" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode40" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode35" pathName="substation1/voltageLevel3/bay14/connvtyNode35" sxy:x="2" sxy:y="0" />
		<ConnectivityNode name="connvtyNode37" pathName="substation1/voltageLevel3/bay14/connvtyNode37" sxy:x="6" sxy:y="0" />
		<ConnectivityNode name="connvtyNode36" pathName="substation1/voltageLevel3/bay14/connvtyNode36" sxy:x="1" sxy:y="3" />
		<ConnectivityNode name="connvtyNode38" pathName="substation1/voltageLevel3/bay14/connvtyNode38" sxy:x="4" sxy:y="5" />
		<ConnectivityNode name="connvtyNode39" pathName="substation1/voltageLevel3/bay14/connvtyNode39" sxy:x="4" sxy:y="6" />
		<ConnectivityNode name="connvtyNode40" pathName="substation1/voltageLevel3/bay14/connvtyNode40" sxy:x="4" sxy:y="8" />
      </Bay>
      <Bay name="bay15" sxy:x="2" sxy:y="1">
		<ConductingEquipment name="AT2SQSG12" type="DIS" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode42" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode42" />
        </ConductingEquipment>
		<ConductingEquipment name="AT2SQS1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode41" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode41" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode42" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode42" />
        </ConductingEquipment>
		<ConductingEquipment name="AT2SQSG11" type="DIS" sxy:x="2" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode41" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode41" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4SQSG11" type="DIS" sxy:x="6" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode43" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode43" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4SQS1" type="DIS" sxy:x="5" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode43" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode43" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode42" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode42" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4SQSG12" type="DIS" sxy:x="5" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode42" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode42" />
        </ConductingEquipment>
		<ConductingEquipment name="GS2QSG2" type="DIS" sxy:x="4" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode42" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode42" />
        </ConductingEquipment>
		<ConductingEquipment name="GS2QS2" type="DIS" sxy:x="3" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode42" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode42" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode44" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode44" />
        </ConductingEquipment>
		<ConductingEquipment name="GS2Q2" type="CBR" sxy:x="3" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode44" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode44" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode45" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode45" />
        </ConductingEquipment>
		<ConductingEquipment name="GS2QSG1" type="DIS" sxy:x="4" sxy:y="6">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode45" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode45" />
        </ConductingEquipment>
		<ConductingEquipment name="GS2QS1" type="DIS" sxy:x="3" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode45" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode45" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode46" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode46" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode41" pathName="substation1/voltageLevel3/bay15/connvtyNode41" sxy:x="1" sxy:y="0" />
		<ConnectivityNode name="connvtyNode43" pathName="substation1/voltageLevel3/bay15/connvtyNode43" sxy:x="5" sxy:y="0" />
		<ConnectivityNode name="connvtyNode42" pathName="substation1/voltageLevel3/bay15/connvtyNode42" sxy:x="1" sxy:y="3" />
		<ConnectivityNode name="connvtyNode44" pathName="substation1/voltageLevel3/bay15/connvtyNode44" sxy:x="3" sxy:y="5" />
		<ConnectivityNode name="connvtyNode45" pathName="substation1/voltageLevel3/bay15/connvtyNode45" sxy:x="3" sxy:y="6" />
		<ConnectivityNode name="connvtyNode46" pathName="substation1/voltageLevel3/bay15/connvtyNode46" sxy:x="3" sxy:y="8" />
      </Bay>
    </VoltageLevel>
	<VoltageLevel name="voltageLevel4" sxy:x="3" sxy:y="39">
      <Voltage unit="V">6</Voltage>
      <Bay name="bay16" sxy:x="3" sxy:y="1">
		<ConductingEquipment name="GS2Q1QSG1" type="DIS" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode46" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode46" />
        </ConductingEquipment>
		<ConductingEquipment name="GS2Q1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay15/connvtyNode46" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay15" cNodeName="connvtyNode46" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel4/bay16/connvtyNode47" substationName="substation1" voltageLevelName="voltageLevel4" bayName="bay16" cNodeName="connvtyNode47" />
        </ConductingEquipment>
		<ConductingEquipment name="conEquipIFL1" type="IFL" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel4/bay16/connvtyNode47" substationName="substation1" voltageLevelName="voltageLevel4" bayName="bay16" cNodeName="connvtyNode47" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode47" pathName="substation1/voltageLevel4/bay16/connvtyNode47" sxy:x="1" sxy:y="2" />
      </Bay>
      <Bay name="bay17" sxy:x="11" sxy:y="1">
		<ConductingEquipment name="GS1Q1QSG1" type="DIS" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode40" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode40" />
        </ConductingEquipment>
		<ConductingEquipment name="GS1Q1" type="DIS" sxy:x="0" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel3/bay14/connvtyNode40" substationName="substation1" voltageLevelName="voltageLevel3" bayName="bay14" cNodeName="connvtyNode40" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel4/bay17/connvtyNode48" substationName="substation1" voltageLevelName="voltageLevel4" bayName="bay17" cNodeName="connvtyNode48" />
        </ConductingEquipment>
		<ConductingEquipment name="conEquipIFL1" type="IFL" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel4/bay17/connvtyNode48" substationName="substation1" voltageLevelName="voltageLevel4" bayName="bay17" cNodeName="connvtyNode48" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode48" pathName="substation1/voltageLevel4/bay17/connvtyNode48" sxy:x="2" sxy:y="2" />
      </Bay>
    </VoltageLevel>
	<VoltageLevel name="voltageLevel2" sxy:x="27" sxy:y="2">
      <Voltage unit="V">220</Voltage>
      <Bay name="bay2" sxy:x="1" sxy:y="1">
		<ConnectivityNode name="connvtyNode49" pathName="substation1/voltageLevel2/bay2/connvtyNode49" sxy:x="1" sxy:y="0" />
      </Bay>
      <Bay name="bay3" sxy:x="1" sxy:y="19">
		<ConnectivityNode name="connvtyNode50" pathName="substation1/voltageLevel2/bay3/connvtyNode50" sxy:x="1" sxy:y="0" />
      </Bay>
      <Bay name="bay4" sxy:x="6" sxy:y="2">
		<ConductingEquipment name="W9EQS1" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay2/connvtyNode49" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay2" cNodeName="connvtyNode49" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode59" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode59" />
        </ConductingEquipment>
		<ConductingEquipment name="W9EQ3" type="CBR" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode59" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode59" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode60" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode60" />
        </ConductingEquipment>
		<ConductingEquipment name="W9EQS2" type="DIS" sxy:x="3" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode60" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode60" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode61" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode61" />
        </ConductingEquipment>
		<ConductingEquipment name="W9AT4EQS1" type="DIS" sxy:x="3" sxy:y="6">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode61" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode61" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode62" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode62" />
        </ConductingEquipment>
		<ConductingEquipment name="W9AT4EQZ1" type="CBR" sxy:x="3" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode62" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode62" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode63" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode63" />
        </ConductingEquipment>
		<ConductingEquipment name="W9AT4EQS2" type="DIS" sxy:x="3" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode63" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode63" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode64" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode64" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4EQS2" type="DIS" sxy:x="3" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode64" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode64" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode65" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode65" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4EQ4" type="CBR" sxy:x="3" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode65" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode65" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode66" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode66" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4EQS1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode66" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode66" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay3/connvtyNode50" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay3" cNodeName="connvtyNode50" />
        </ConductingEquipment>
		<ConductingEquipment name="W9EQSG1" type="DIS" sxy:x="4" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode59" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode59" />
        </ConductingEquipment>
		<ConductingEquipment name="W9EQSG21" type="DIS" sxy:x="4" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode60" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode60" />
        </ConductingEquipment>
		<ConductingEquipment name="W9AT4EQSG1" type="DIS" sxy:x="4" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode62" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode62" />
        </ConductingEquipment>
		<ConductingEquipment name="W9AT4EQSG2" type="DIS" sxy:x="4" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode63" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode63" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4EQSG22" type="DIS" sxy:x="3" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode64" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode64" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4EQSG21" type="DIS" sxy:x="3" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode65" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode65" />
        </ConductingEquipment>
		<ConductingEquipment name="AT4EQSG1" type="DIS" sxy:x="3" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode66" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode66" />
        </ConductingEquipment>
		<ConductingEquipment name="W9EQSG22" type="DIS" sxy:x="3" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode61" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode61" />
        </ConductingEquipment>
		<ConductingEquipment name="W9E" type="IFL" sxy:x="4" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay4/connvtyNode61" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay4" cNodeName="connvtyNode61" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode59" pathName="substation1/voltageLevel2/bay4/connvtyNode59" sxy:x="2" sxy:y="2" />
		<ConnectivityNode name="connvtyNode60" pathName="substation1/voltageLevel2/bay4/connvtyNode60" sxy:x="3" sxy:y="3" />
		<ConnectivityNode name="connvtyNode61" pathName="substation1/voltageLevel2/bay4/connvtyNode61" sxy:x="2" sxy:y="5" />
		<ConnectivityNode name="connvtyNode62" pathName="substation1/voltageLevel2/bay4/connvtyNode62" sxy:x="2" sxy:y="8" />
		<ConnectivityNode name="connvtyNode63" pathName="substation1/voltageLevel2/bay4/connvtyNode63" sxy:x="3" sxy:y="9" />
		<ConnectivityNode name="connvtyNode64" pathName="substation1/voltageLevel2/bay4/connvtyNode64" sxy:x="1" sxy:y="11" />
		<ConnectivityNode name="connvtyNode65" pathName="substation1/voltageLevel2/bay4/connvtyNode65" sxy:x="3" sxy:y="13" />
		<ConnectivityNode name="connvtyNode66" pathName="substation1/voltageLevel2/bay4/connvtyNode66" sxy:x="3" sxy:y="14" />
      </Bay>
      <Bay name="bay5" sxy:x="10" sxy:y="4">
		<ConductingEquipment name="AT2EQS1" type="DIS" sxy:x="3" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay2/connvtyNode49" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay2" cNodeName="connvtyNode49" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode67" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode67" />
        </ConductingEquipment>
		<ConductingEquipment name="AT2EQ3" type="CBR" sxy:x="3" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode67" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode67" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode68" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode68" />
        </ConductingEquipment>
		<ConductingEquipment name="AT2EQS2" type="DIS" sxy:x="3" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode68" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode68" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode69" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode69" />
        </ConductingEquipment>
		<ConductingEquipment name="W8AT2EQS1" type="DIS" sxy:x="3" sxy:y="6">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode69" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode69" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode70" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode70" />
        </ConductingEquipment>
		<ConductingEquipment name="W8AT2EQZ1" type="CBR" sxy:x="2" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode70" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode70" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode71" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode71" />
        </ConductingEquipment>
		<ConductingEquipment name="W8AT2EQS2" type="DIS" sxy:x="2" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode71" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode71" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode72" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode72" />
        </ConductingEquipment>
		<ConductingEquipment name="W8EQS2" type="DIS" sxy:x="3" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode72" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode72" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode73" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode73" />
        </ConductingEquipment>
		<ConductingEquipment name="W8EQ4" type="CBR" sxy:x="3" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode73" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode73" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode74" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode74" />
        </ConductingEquipment>
		<ConductingEquipment name="W8EQS1" type="DIS" sxy:x="3" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode74" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode74" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay3/connvtyNode50" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay3" cNodeName="connvtyNode50" />
        </ConductingEquipment>
		<ConductingEquipment name="AT2EQSG1" type="DIS" sxy:x="3" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode67" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode67" />
        </ConductingEquipment>
		<ConductingEquipment name="AT2EQSG21" type="DIS" sxy:x="4" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode68" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode68" />
        </ConductingEquipment>
		<ConductingEquipment name="W8AT2EQSG1" type="DIS" sxy:x="4" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode70" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode70" />
        </ConductingEquipment>
		<ConductingEquipment name="W8AT2EQSG2" type="DIS" sxy:x="3" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode71" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode71" />
        </ConductingEquipment>
		<ConductingEquipment name="W8EQSG22" type="DIS" sxy:x="3" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode72" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode72" />
        </ConductingEquipment>
		<ConductingEquipment name="W8EQSG21" type="DIS" sxy:x="3" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode73" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode73" />
        </ConductingEquipment>
		<ConductingEquipment name="W8EQSG1" type="DIS" sxy:x="3" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode74" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode74" />
        </ConductingEquipment>
		<ConductingEquipment name="AT2EQSG22" type="DIS" sxy:x="3" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode69" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode69" />
        </ConductingEquipment>
		<ConductingEquipment name="W8E" type="IFL" sxy:x="4" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay5/connvtyNode72" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay5" cNodeName="connvtyNode72" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode67" pathName="substation1/voltageLevel2/bay5/connvtyNode67" sxy:x="2" sxy:y="2" />
		<ConnectivityNode name="connvtyNode68" pathName="substation1/voltageLevel2/bay5/connvtyNode68" sxy:x="3" sxy:y="3" />
		<ConnectivityNode name="connvtyNode69" pathName="substation1/voltageLevel2/bay5/connvtyNode69" sxy:x="0" sxy:y="5" />
		<ConnectivityNode name="connvtyNode70" pathName="substation1/voltageLevel2/bay5/connvtyNode70" sxy:x="2" sxy:y="8" />
		<ConnectivityNode name="connvtyNode71" pathName="substation1/voltageLevel2/bay5/connvtyNode71" sxy:x="3" sxy:y="9" />
		<ConnectivityNode name="connvtyNode72" pathName="substation1/voltageLevel2/bay5/connvtyNode72" sxy:x="2" sxy:y="11" />
		<ConnectivityNode name="connvtyNode73" pathName="substation1/voltageLevel2/bay5/connvtyNode73" sxy:x="3" sxy:y="13" />
		<ConnectivityNode name="connvtyNode74" pathName="substation1/voltageLevel2/bay5/connvtyNode74" sxy:x="3" sxy:y="14" />
      </Bay>
      <Bay name="bay1" sxy:x="1" sxy:y="5">
		<ConductingEquipment name="T2EQS1" type="DIS" sxy:x="0" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay2/connvtyNode49" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay2" cNodeName="connvtyNode49" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode51" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode51" />
        </ConductingEquipment>
		<ConductingEquipment name="T2EQ3" type="CBR" sxy:x="0" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode51" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode51" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode52" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode52" />
        </ConductingEquipment>
		<ConductingEquipment name="T2EQS2" type="DIS" sxy:x="0" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode52" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode52" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode53" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode53" />
        </ConductingEquipment>
		<ConductingEquipment name="W10T2EQS1" type="DIS" sxy:x="0" sxy:y="6">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode53" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode53" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode54" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode54" />
        </ConductingEquipment>
		<ConductingEquipment name="W10T2EQZ1" type="CBR" sxy:x="0" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode54" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode54" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode55" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode55" />
        </ConductingEquipment>
		<ConductingEquipment name="W10T2EQS2" type="DIS" sxy:x="0" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode55" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode55" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode56" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode56" />
        </ConductingEquipment>
		<ConductingEquipment name="W10EQS2" type="DIS" sxy:x="0" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode56" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode56" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode57" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode57" />
        </ConductingEquipment>
		<ConductingEquipment name="W10EQ4" type="CBR" sxy:x="0" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode57" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode57" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode58" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode58" />
        </ConductingEquipment>
		<ConductingEquipment name="W10EQS1" type="DIS" sxy:x="1" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode58" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode58" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay3/connvtyNode50" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay3" cNodeName="connvtyNode50" />
        </ConductingEquipment>
		<ConductingEquipment name="K3EQSG1" type="DIS" sxy:x="2" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay2/connvtyNode49" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay2" cNodeName="connvtyNode49" />
        </ConductingEquipment>
		<ConductingEquipment name="T2EQSG1" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode51" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode51" />
        </ConductingEquipment>
		<ConductingEquipment name="T2EQSG21" type="DIS" sxy:x="1" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode52" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode52" />
        </ConductingEquipment>
		<ConductingEquipment name="T2EQSG22" type="DIS" sxy:x="2" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode53" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode53" />
        </ConductingEquipment>
		<ConductingEquipment name="W10T2EQSG1" type="DIS" sxy:x="1" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode54" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode54" />
        </ConductingEquipment>
		<ConductingEquipment name="W10T2EQSG2" type="DIS" sxy:x="1" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode55" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode55" />
        </ConductingEquipment>
		<ConductingEquipment name="W10EQSG22" type="DIS" sxy:x="1" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode56" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode56" />
        </ConductingEquipment>
		<ConductingEquipment name="W10EQSG21" type="DIS" sxy:x="1" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode57" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode57" />
        </ConductingEquipment>
		<ConductingEquipment name="W10EQSG1" type="DIS" sxy:x="2" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay1/connvtyNode58" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay1" cNodeName="connvtyNode58" />
        </ConductingEquipment>
		<ConductingEquipment name="K4EQSG1" type="DIS" sxy:x="2" sxy:y="16">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay3/connvtyNode50" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay3" cNodeName="connvtyNode50" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode51" pathName="substation1/voltageLevel2/bay1/connvtyNode51" sxy:x="1" sxy:y="1" />
		<ConnectivityNode name="connvtyNode52" pathName="substation1/voltageLevel2/bay1/connvtyNode52" sxy:x="1" sxy:y="3" />
		<ConnectivityNode name="connvtyNode53" pathName="substation1/voltageLevel2/bay1/connvtyNode53" sxy:x="1" sxy:y="5" />
		<ConnectivityNode name="connvtyNode54" pathName="substation1/voltageLevel2/bay1/connvtyNode54" sxy:x="1" sxy:y="7" />
		<ConnectivityNode name="connvtyNode55" pathName="substation1/voltageLevel2/bay1/connvtyNode55" sxy:x="1" sxy:y="9" />
		<ConnectivityNode name="connvtyNode56" pathName="substation1/voltageLevel2/bay1/connvtyNode56" sxy:x="1" sxy:y="11" />
		<ConnectivityNode name="connvtyNode57" pathName="substation1/voltageLevel2/bay1/connvtyNode57" sxy:x="1" sxy:y="13" />
		<ConnectivityNode name="connvtyNode58" pathName="substation1/voltageLevel2/bay1/connvtyNode58" sxy:x="1" sxy:y="14" />
      </Bay>
      <Bay name="bay6" sxy:x="15" sxy:y="5">
		<ConductingEquipment name="AT5EQS1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay2/connvtyNode49" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay2" cNodeName="connvtyNode49" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode75" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode75" />
        </ConductingEquipment>
		<ConductingEquipment name="AT5EQ3" type="CBR" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode75" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode75" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode76" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode76" />
        </ConductingEquipment>
		<ConductingEquipment name="AT5EQS2" type="DIS" sxy:x="2" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode76" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode76" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode77" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode77" />
        </ConductingEquipment>
		<ConductingEquipment name="W7AT5EQS1" type="DIS" sxy:x="1" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode77" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode77" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode78" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode78" />
        </ConductingEquipment>
		<ConductingEquipment name="W7AT5EQZ1" type="CBR" sxy:x="1" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode78" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode78" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode79" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode79" />
        </ConductingEquipment>
		<ConductingEquipment name="W7AT5EQS2" type="DIS" sxy:x="1" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode79" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode79" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode80" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode80" />
        </ConductingEquipment>
		<ConductingEquipment name="W7EQS2" type="DIS" sxy:x="1" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode80" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode80" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode81" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode81" />
        </ConductingEquipment>
		<ConductingEquipment name="W7EQ4" type="CBR" sxy:x="1" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode81" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode81" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode82" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode82" />
        </ConductingEquipment>
		<ConductingEquipment name="W7EQS1" type="DIS" sxy:x="1" sxy:y="16">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode82" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode82" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay3/connvtyNode50" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay3" cNodeName="connvtyNode50" />
        </ConductingEquipment>
		<ConductingEquipment name="AT5EQSG1" type="DIS" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode75" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode75" />
        </ConductingEquipment>
		<ConductingEquipment name="AT5EQSG21" type="DIS" sxy:x="3" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode76" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode76" />
        </ConductingEquipment>
		<ConductingEquipment name="W7AT5EQSG1" type="DIS" sxy:x="2" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode78" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode78" />
        </ConductingEquipment>
		<ConductingEquipment name="W7AT5EQSG2" type="DIS" sxy:x="3" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode79" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode79" />
        </ConductingEquipment>
		<ConductingEquipment name="W7EQSG22" type="DIS" sxy:x="3" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode80" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode80" />
        </ConductingEquipment>
		<ConductingEquipment name="W7EQSG21" type="DIS" sxy:x="2" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode81" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode81" />
        </ConductingEquipment>
		<ConductingEquipment name="W7EQSG1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode82" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode82" />
        </ConductingEquipment>
		<ConductingEquipment name="AT5EQSG22" type="DIS" sxy:x="2" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode77" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode77" />
        </ConductingEquipment>
		<ConductingEquipment name="W7E" type="IFL" sxy:x="3" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay6/connvtyNode80" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay6" cNodeName="connvtyNode80" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode75" pathName="substation1/voltageLevel2/bay6/connvtyNode75" sxy:x="2" sxy:y="2" />
		<ConnectivityNode name="connvtyNode76" pathName="substation1/voltageLevel2/bay6/connvtyNode76" sxy:x="2" sxy:y="4" />
		<ConnectivityNode name="connvtyNode77" pathName="substation1/voltageLevel2/bay6/connvtyNode77" sxy:x="1" sxy:y="5" />
		<ConnectivityNode name="connvtyNode78" pathName="substation1/voltageLevel2/bay6/connvtyNode78" sxy:x="2" sxy:y="8" />
		<ConnectivityNode name="connvtyNode79" pathName="substation1/voltageLevel2/bay6/connvtyNode79" sxy:x="2" sxy:y="10" />
		<ConnectivityNode name="connvtyNode80" pathName="substation1/voltageLevel2/bay6/connvtyNode80" sxy:x="1" sxy:y="12" />
		<ConnectivityNode name="connvtyNode81" pathName="substation1/voltageLevel2/bay6/connvtyNode81" sxy:x="2" sxy:y="13" />
		<ConnectivityNode name="connvtyNode82" pathName="substation1/voltageLevel2/bay6/connvtyNode82" sxy:x="2" sxy:y="14" />
      </Bay>
      <Bay name="bay7" sxy:x="20" sxy:y="2">
		<ConductingEquipment name="W6EQS1" type="DIS" sxy:x="2" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay2/connvtyNode49" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay2" cNodeName="connvtyNode49" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode83" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode83" />
        </ConductingEquipment>
		<ConductingEquipment name="W6EQ3" type="CBR" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode83" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode83" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode84" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode84" />
        </ConductingEquipment>
		<ConductingEquipment name="W6EQS2" type="DIS" sxy:x="1" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode84" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode84" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode85" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode85" />
        </ConductingEquipment>
		<ConductingEquipment name="W6T1EQS1" type="DIS" sxy:x="1" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode85" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode85" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode86" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode86" />
        </ConductingEquipment>
		<ConductingEquipment name="W6T1EQZ1" type="CBR" sxy:x="2" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode86" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode86" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode87" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode87" />
        </ConductingEquipment>
		<ConductingEquipment name="W6T1EQS3" type="DIS" sxy:x="2" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode87" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode87" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode88" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode88" />
        </ConductingEquipment>
		<ConductingEquipment name="T1EQS2" type="DIS" sxy:x="1" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode88" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode88" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode89" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode89" />
        </ConductingEquipment>
		<ConductingEquipment name="T1EQ4" type="CBR" sxy:x="1" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode89" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode89" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode90" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode90" />
        </ConductingEquipment>
		<ConductingEquipment name="T1EQS1" type="DIS" sxy:x="1" sxy:y="16">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode90" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode90" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay3/connvtyNode50" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay3" cNodeName="connvtyNode50" />
        </ConductingEquipment>
		<ConductingEquipment name="W6EQSG1" type="DIS" sxy:x="3" sxy:y="-2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode83" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode83" />
        </ConductingEquipment>
		<ConductingEquipment name="W6EQSG21" type="DIS" sxy:x="2" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode84" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode84" />
        </ConductingEquipment>
		<ConductingEquipment name="W6T1EQSG1" type="DIS" sxy:x="3" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode86" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode86" />
        </ConductingEquipment>
		<ConductingEquipment name="W6T1EQSG2" type="DIS" sxy:x="2" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode87" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode87" />
        </ConductingEquipment>
		<ConductingEquipment name="T1EQSG22" type="DIS" sxy:x="2" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode88" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode88" />
        </ConductingEquipment>
		<ConductingEquipment name="T1EQSG21" type="DIS" sxy:x="2" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode89" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode89" />
        </ConductingEquipment>
		<ConductingEquipment name="T1EQSG1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode90" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode90" />
        </ConductingEquipment>
		<ConductingEquipment name="W6EQSG22" type="DIS" sxy:x="2" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode85" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode85" />
        </ConductingEquipment>
		<ConductingEquipment name="W6E" type="IFL" sxy:x="0" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay7/connvtyNode88" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay7" cNodeName="connvtyNode88" />
        </ConductingEquipment>
		<ConductingEquipment name="K3EQSG2" type="DIS" sxy:x="3" sxy:y="-3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay2/connvtyNode49" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay2" cNodeName="connvtyNode49" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode83" pathName="substation1/voltageLevel2/bay7/connvtyNode83" sxy:x="2" sxy:y="1" />
		<ConnectivityNode name="connvtyNode84" pathName="substation1/voltageLevel2/bay7/connvtyNode84" sxy:x="1" sxy:y="4" />
		<ConnectivityNode name="connvtyNode85" pathName="substation1/voltageLevel2/bay7/connvtyNode85" sxy:x="0" sxy:y="5" />
		<ConnectivityNode name="connvtyNode86" pathName="substation1/voltageLevel2/bay7/connvtyNode86" sxy:x="2" sxy:y="7" />
		<ConnectivityNode name="connvtyNode87" pathName="substation1/voltageLevel2/bay7/connvtyNode87" sxy:x="1" sxy:y="10" />
		<ConnectivityNode name="connvtyNode88" pathName="substation1/voltageLevel2/bay7/connvtyNode88" sxy:x="1" sxy:y="11" />
		<ConnectivityNode name="connvtyNode89" pathName="substation1/voltageLevel2/bay7/connvtyNode89" sxy:x="1" sxy:y="13" />
		<ConnectivityNode name="connvtyNode90" pathName="substation1/voltageLevel2/bay7/connvtyNode90" sxy:x="1" sxy:y="15" />
      </Bay>
      <Bay name="bay8" sxy:x="25" sxy:y="2">
		<ConductingEquipment name="QC1EQSG2" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay8/connvtyNode91" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay8" cNodeName="connvtyNode91" />
        </ConductingEquipment>
		<ConductingEquipment name="QC1EQS2" type="DIS" sxy:x="0" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay2/connvtyNode49" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay2" cNodeName="connvtyNode49" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay8/connvtyNode91" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay8" cNodeName="connvtyNode91" />
        </ConductingEquipment>
		<ConductingEquipment name="QC1E" type="CBR" sxy:x="0" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay8/connvtyNode91" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay8" cNodeName="connvtyNode91" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay10/connvtyNode93" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay10" cNodeName="connvtyNode93" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode91" pathName="substation1/voltageLevel2/bay8/connvtyNode91" sxy:x="1" sxy:y="1" />
      </Bay>
      <Bay name="bay9" sxy:x="25" sxy:y="15">
		<ConductingEquipment name="QC2EQSG2" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay9/connvtyNode92" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay9" cNodeName="connvtyNode92" />
        </ConductingEquipment>
		<ConductingEquipment name="QC2EQS2" type="DIS" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay9/connvtyNode92" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay9" cNodeName="connvtyNode92" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay3/connvtyNode50" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay3" cNodeName="connvtyNode50" />
        </ConductingEquipment>
		<ConductingEquipment name="QC2E" type="CBR" sxy:x="1" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay9/connvtyNode92" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay9" cNodeName="connvtyNode92" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay3/connvtyNode50" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay3" cNodeName="connvtyNode50" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode92" pathName="substation1/voltageLevel2/bay9/connvtyNode92" sxy:x="0" sxy:y="2" />
      </Bay>
      <Bay name="bay10" sxy:x="28" sxy:y="2">
		<ConductingEquipment name="QC1EQSG1" type="DIS" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay10/connvtyNode93" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay10" cNodeName="connvtyNode93" />
        </ConductingEquipment>
		<ConductingEquipment name="QC1EQS1" type="DIS" sxy:x="0" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay12/connvtyNode95" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay12" cNodeName="connvtyNode95" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay10/connvtyNode93" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay10" cNodeName="connvtyNode93" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode93" pathName="substation1/voltageLevel2/bay10/connvtyNode93" sxy:x="1" sxy:y="1" />
      </Bay>
      <Bay name="bay11" sxy:x="28" sxy:y="15">
		<ConductingEquipment name="QC2EQSG1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay11/connvtyNode94" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay11" cNodeName="connvtyNode94" />
        </ConductingEquipment>
		<ConductingEquipment name="QC2EQS21" type="DIS" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay11/connvtyNode94" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay11" cNodeName="connvtyNode94" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay13/connvtyNode96" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay13" cNodeName="connvtyNode96" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode94" pathName="substation1/voltageLevel2/bay11/connvtyNode94" sxy:x="1" sxy:y="1" />
      </Bay>
      <Bay name="bay12" sxy:x="28" sxy:y="1">
		<ConnectivityNode name="connvtyNode95" pathName="substation1/voltageLevel2/bay12/connvtyNode95" sxy:x="1" sxy:y="0" />
      </Bay>
      <Bay name="bay13" sxy:x="28" sxy:y="19">
		<ConnectivityNode name="connvtyNode96" pathName="substation1/voltageLevel2/bay13/connvtyNode96" sxy:x="0" sxy:y="0" />
      </Bay>
      <Bay name="bay14" sxy:x="30" sxy:y="2">
		<ConductingEquipment name="W5EQS1" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay12/connvtyNode95" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay12" cNodeName="connvtyNode95" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode97" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode97" />
        </ConductingEquipment>
		<ConductingEquipment name="W5EQ1" type="CBR" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode97" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode97" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode98" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode98" />
        </ConductingEquipment>
		<ConductingEquipment name="W5EQS2" type="DIS" sxy:x="1" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode98" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode98" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode99" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode99" />
        </ConductingEquipment>
		<ConductingEquipment name="W5AT3EQS1" type="DIS" sxy:x="1" sxy:y="6">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode99" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode99" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode100" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode100" />
        </ConductingEquipment>
		<ConductingEquipment name="W5AT3EQZ1" type="CBR" sxy:x="2" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode100" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode100" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode101" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode101" />
        </ConductingEquipment>
		<ConductingEquipment name="W5AT3EQS2" type="DIS" sxy:x="2" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode101" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode101" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode102" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode102" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3EQS2" type="DIS" sxy:x="1" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode102" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode102" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode103" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode103" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3EQ2" type="CBR" sxy:x="1" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode103" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode103" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode104" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode104" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3EQS1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode104" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode104" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay13/connvtyNode96" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay13" cNodeName="connvtyNode96" />
        </ConductingEquipment>
		<ConductingEquipment name="W5EQSG1" type="DIS" sxy:x="3" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode97" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode97" />
        </ConductingEquipment>
		<ConductingEquipment name="W5EQSG21" type="DIS" sxy:x="2" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode98" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode98" />
        </ConductingEquipment>
		<ConductingEquipment name="W5AT3EQSG1" type="DIS" sxy:x="3" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode100" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode100" />
        </ConductingEquipment>
		<ConductingEquipment name="W5AT3EQSG2" type="DIS" sxy:x="2" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode101" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode101" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3EQSG22" type="DIS" sxy:x="2" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode102" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode102" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3EQSG21" type="DIS" sxy:x="3" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode103" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode103" />
        </ConductingEquipment>
		<ConductingEquipment name="AT3EQSG1" type="DIS" sxy:x="2" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode104" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode104" />
        </ConductingEquipment>
		<ConductingEquipment name="W5EQSG22" type="DIS" sxy:x="2" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode99" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode99" />
        </ConductingEquipment>
		<ConductingEquipment name="W5E" type="IFL" sxy:x="1" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay14/connvtyNode99" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay14" cNodeName="connvtyNode99" />
        </ConductingEquipment>
		<ConductingEquipment name="K1EQSG2" type="DIS" sxy:x="2" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay12/connvtyNode95" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay12" cNodeName="connvtyNode95" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode97" pathName="substation1/voltageLevel2/bay14/connvtyNode97" sxy:x="2" sxy:y="2" />
		<ConnectivityNode name="connvtyNode98" pathName="substation1/voltageLevel2/bay14/connvtyNode98" sxy:x="2" sxy:y="3" />
		<ConnectivityNode name="connvtyNode99" pathName="substation1/voltageLevel2/bay14/connvtyNode99" sxy:x="1" sxy:y="5" />
		<ConnectivityNode name="connvtyNode100" pathName="substation1/voltageLevel2/bay14/connvtyNode100" sxy:x="2" sxy:y="7" />
		<ConnectivityNode name="connvtyNode101" pathName="substation1/voltageLevel2/bay14/connvtyNode101" sxy:x="2" sxy:y="9" />
		<ConnectivityNode name="connvtyNode102" pathName="substation1/voltageLevel2/bay14/connvtyNode102" sxy:x="1" sxy:y="11" />
		<ConnectivityNode name="connvtyNode103" pathName="substation1/voltageLevel2/bay14/connvtyNode103" sxy:x="2" sxy:y="13" />
		<ConnectivityNode name="connvtyNode104" pathName="substation1/voltageLevel2/bay14/connvtyNode104" sxy:x="2" sxy:y="15" />
      </Bay>
      <Bay name="bay15" sxy:x="35" sxy:y="2">
		<ConductingEquipment name="W4EQS1" type="DIS" sxy:x="2" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay12/connvtyNode95" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay12" cNodeName="connvtyNode95" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode105" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode105" />
        </ConductingEquipment>
		<ConductingEquipment name="W4EQ1" type="CBR" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode105" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode105" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode106" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode106" />
        </ConductingEquipment>
		<ConductingEquipment name="W4EQS2" type="DIS" sxy:x="1" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode106" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode106" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode107" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode107" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT6EQS1" type="DIS" sxy:x="2" sxy:y="6">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode107" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode107" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode108" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode108" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT6EQZ1" type="CBR" sxy:x="2" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode108" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode108" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode109" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode109" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT6EQS2" type="DIS" sxy:x="1" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode109" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode109" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode110" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode110" />
        </ConductingEquipment>
		<ConductingEquipment name="AT6EQS2" type="DIS" sxy:x="1" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode110" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode110" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode111" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode111" />
        </ConductingEquipment>
		<ConductingEquipment name="AT6EQ2" type="CBR" sxy:x="2" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode111" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode111" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode112" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode112" />
        </ConductingEquipment>
		<ConductingEquipment name="AT6EQS1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode112" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode112" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay13/connvtyNode96" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay13" cNodeName="connvtyNode96" />
        </ConductingEquipment>
		<ConductingEquipment name="W4EQSG1" type="DIS" sxy:x="3" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode105" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode105" />
        </ConductingEquipment>
		<ConductingEquipment name="W4EQSG21" type="DIS" sxy:x="3" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode106" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode106" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT6EQSG1" type="DIS" sxy:x="2" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode108" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode108" />
        </ConductingEquipment>
		<ConductingEquipment name="W4AT6EQSG2" type="DIS" sxy:x="3" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode109" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode109" />
        </ConductingEquipment>
		<ConductingEquipment name="AT6EQSG22" type="DIS" sxy:x="2" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode110" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode110" />
        </ConductingEquipment>
		<ConductingEquipment name="AT6EQSG21" type="DIS" sxy:x="3" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode111" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode111" />
        </ConductingEquipment>
		<ConductingEquipment name="AT6EQSG1" type="DIS" sxy:x="3" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode112" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode112" />
        </ConductingEquipment>
		<ConductingEquipment name="W4EQSG22" type="DIS" sxy:x="3" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode107" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode107" />
        </ConductingEquipment>
		<ConductingEquipment name="W4E" type="IFL" sxy:x="1" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay15/connvtyNode107" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay15" cNodeName="connvtyNode107" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode105" pathName="substation1/voltageLevel2/bay15/connvtyNode105" sxy:x="2" sxy:y="1" />
		<ConnectivityNode name="connvtyNode106" pathName="substation1/voltageLevel2/bay15/connvtyNode106" sxy:x="2" sxy:y="3" />
		<ConnectivityNode name="connvtyNode107" pathName="substation1/voltageLevel2/bay15/connvtyNode107" sxy:x="1" sxy:y="5" />
		<ConnectivityNode name="connvtyNode108" pathName="substation1/voltageLevel2/bay15/connvtyNode108" sxy:x="2" sxy:y="7" />
		<ConnectivityNode name="connvtyNode109" pathName="substation1/voltageLevel2/bay15/connvtyNode109" sxy:x="2" sxy:y="10" />
		<ConnectivityNode name="connvtyNode110" pathName="substation1/voltageLevel2/bay15/connvtyNode110" sxy:x="1" sxy:y="11" />
		<ConnectivityNode name="connvtyNode111" pathName="substation1/voltageLevel2/bay15/connvtyNode111" sxy:x="2" sxy:y="13" />
		<ConnectivityNode name="connvtyNode112" pathName="substation1/voltageLevel2/bay15/connvtyNode112" sxy:x="2" sxy:y="15" />
      </Bay>
      <Bay name="bay16" sxy:x="40" sxy:y="2">
		<ConductingEquipment name="AT1EQS1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay12/connvtyNode95" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay12" cNodeName="connvtyNode95" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode113" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode113" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1EQ1" type="CBR" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode113" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode113" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode114" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode114" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1EQS2" type="DIS" sxy:x="1" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode114" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode114" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode115" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode115" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1EQS1" type="DIS" sxy:x="1" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode115" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode115" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode116" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode116" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1EQZ1" type="CBR" sxy:x="1" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode116" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode116" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode117" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode117" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1EQS2" type="DIS" sxy:x="1" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode117" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode117" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode118" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode118" />
        </ConductingEquipment>
		<ConductingEquipment name="W3EQS2" type="DIS" sxy:x="1" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode118" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode118" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode119" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode119" />
        </ConductingEquipment>
		<ConductingEquipment name="W3EQ2" type="CBR" sxy:x="1" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode119" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode119" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode120" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode120" />
        </ConductingEquipment>
		<ConductingEquipment name="W3EQS1" type="DIS" sxy:x="1" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode120" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode120" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay13/connvtyNode96" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay13" cNodeName="connvtyNode96" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1EQSG1" type="DIS" sxy:x="2" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode113" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode113" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1EQSG21" type="DIS" sxy:x="2" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode114" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode114" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1EQSG1" type="DIS" sxy:x="2" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode116" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode116" />
        </ConductingEquipment>
		<ConductingEquipment name="W3AT1EQSG2" type="DIS" sxy:x="2" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode117" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode117" />
        </ConductingEquipment>
		<ConductingEquipment name="W3EQSG22" type="DIS" sxy:x="2" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode118" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode118" />
        </ConductingEquipment>
		<ConductingEquipment name="W3EQSG21" type="DIS" sxy:x="2" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode119" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode119" />
        </ConductingEquipment>
		<ConductingEquipment name="W3EQSG1" type="DIS" sxy:x="2" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode120" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode120" />
        </ConductingEquipment>
		<ConductingEquipment name="AT1EQSG22" type="DIS" sxy:x="2" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode115" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode115" />
        </ConductingEquipment>
		<ConductingEquipment name="W3E" type="IFL" sxy:x="3" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay16/connvtyNode118" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay16" cNodeName="connvtyNode118" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode113" pathName="substation1/voltageLevel2/bay16/connvtyNode113" sxy:x="1" sxy:y="1" />
		<ConnectivityNode name="connvtyNode114" pathName="substation1/voltageLevel2/bay16/connvtyNode114" sxy:x="2" sxy:y="3" />
		<ConnectivityNode name="connvtyNode115" pathName="substation1/voltageLevel2/bay16/connvtyNode115" sxy:x="0" sxy:y="5" />
		<ConnectivityNode name="connvtyNode116" pathName="substation1/voltageLevel2/bay16/connvtyNode116" sxy:x="2" sxy:y="8" />
		<ConnectivityNode name="connvtyNode117" pathName="substation1/voltageLevel2/bay16/connvtyNode117" sxy:x="1" sxy:y="10" />
		<ConnectivityNode name="connvtyNode118" pathName="substation1/voltageLevel2/bay16/connvtyNode118" sxy:x="0" sxy:y="11" />
		<ConnectivityNode name="connvtyNode119" pathName="substation1/voltageLevel2/bay16/connvtyNode119" sxy:x="2" sxy:y="13" />
		<ConnectivityNode name="connvtyNode120" pathName="substation1/voltageLevel2/bay16/connvtyNode120" sxy:x="1" sxy:y="15" />
      </Bay>
      <Bay name="bay17" sxy:x="44" sxy:y="2">
		<ConductingEquipment name="T4EQS1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay12/connvtyNode95" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay12" cNodeName="connvtyNode95" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode121" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode121" />
        </ConductingEquipment>
		<ConductingEquipment name="T4EQ1" type="CBR" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode121" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode121" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode122" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode122" />
        </ConductingEquipment>
		<ConductingEquipment name="T4EQS2" type="DIS" sxy:x="1" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode122" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode122" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode123" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode123" />
        </ConductingEquipment>
		<ConductingEquipment name="W2T4EQS1" type="DIS" sxy:x="1" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode123" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode123" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode124" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode124" />
        </ConductingEquipment>
		<ConductingEquipment name="W2T4EQZ1" type="CBR" sxy:x="2" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode124" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode124" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode125" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode125" />
        </ConductingEquipment>
		<ConductingEquipment name="W2T4EQS2" type="DIS" sxy:x="2" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode125" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode125" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode126" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode126" />
        </ConductingEquipment>
		<ConductingEquipment name="W2EQS2" type="DIS" sxy:x="1" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode126" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode126" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode127" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode127" />
        </ConductingEquipment>
		<ConductingEquipment name="W2EQ2" type="CBR" sxy:x="1" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode127" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode127" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode128" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode128" />
        </ConductingEquipment>
		<ConductingEquipment name="W2EQS1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode128" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode128" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay13/connvtyNode96" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay13" cNodeName="connvtyNode96" />
        </ConductingEquipment>
		<ConductingEquipment name="T4EQSG1" type="DIS" sxy:x="3" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode121" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode121" />
        </ConductingEquipment>
		<ConductingEquipment name="T4EQSG21" type="DIS" sxy:x="2" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode122" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode122" />
        </ConductingEquipment>
		<ConductingEquipment name="W2T4EQSG1" type="DIS" sxy:x="2" sxy:y="8">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode124" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode124" />
        </ConductingEquipment>
		<ConductingEquipment name="W2T4EQSG2" type="DIS" sxy:x="2" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode125" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode125" />
        </ConductingEquipment>
		<ConductingEquipment name="W2EQSG22" type="DIS" sxy:x="2" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode126" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode126" />
        </ConductingEquipment>
		<ConductingEquipment name="W2EQSG21" type="DIS" sxy:x="2" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode127" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode127" />
        </ConductingEquipment>
		<ConductingEquipment name="W2EQSG1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode128" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode128" />
        </ConductingEquipment>
		<ConductingEquipment name="T4EQSG22" type="DIS" sxy:x="2" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode123" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode123" />
        </ConductingEquipment>
		<ConductingEquipment name="W2E" type="IFL" sxy:x="3" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay17/connvtyNode126" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay17" cNodeName="connvtyNode126" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode121" pathName="substation1/voltageLevel2/bay17/connvtyNode121" sxy:x="2" sxy:y="2" />
		<ConnectivityNode name="connvtyNode122" pathName="substation1/voltageLevel2/bay17/connvtyNode122" sxy:x="2" sxy:y="4" />
		<ConnectivityNode name="connvtyNode123" pathName="substation1/voltageLevel2/bay17/connvtyNode123" sxy:x="0" sxy:y="6" />
		<ConnectivityNode name="connvtyNode124" pathName="substation1/voltageLevel2/bay17/connvtyNode124" sxy:x="2" sxy:y="8" />
		<ConnectivityNode name="connvtyNode125" pathName="substation1/voltageLevel2/bay17/connvtyNode125" sxy:x="2" sxy:y="10" />
		<ConnectivityNode name="connvtyNode126" pathName="substation1/voltageLevel2/bay17/connvtyNode126" sxy:x="1" sxy:y="12" />
		<ConnectivityNode name="connvtyNode127" pathName="substation1/voltageLevel2/bay17/connvtyNode127" sxy:x="2" sxy:y="13" />
		<ConnectivityNode name="connvtyNode128" pathName="substation1/voltageLevel2/bay17/connvtyNode128" sxy:x="2" sxy:y="15" />
      </Bay>
      <Bay name="bay18" sxy:x="49" sxy:y="2">
		<ConductingEquipment name="W1EQS1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay12/connvtyNode95" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay12" cNodeName="connvtyNode95" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode129" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode129" />
        </ConductingEquipment>
		<ConductingEquipment name="W1EQ1" type="CBR" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode129" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode129" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode130" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode130" />
        </ConductingEquipment>
		<ConductingEquipment name="W1EQS2" type="DIS" sxy:x="1" sxy:y="4">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode130" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode130" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode131" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode131" />
        </ConductingEquipment>
		<ConductingEquipment name="W1T3EQS1" type="DIS" sxy:x="1" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode131" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode131" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode132" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode132" />
        </ConductingEquipment>
		<ConductingEquipment name="W1T3EQZ1" type="CBR" sxy:x="1" sxy:y="9">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode132" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode132" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode133" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode133" />
        </ConductingEquipment>
		<ConductingEquipment name="W1T3EQS2" type="DIS" sxy:x="1" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode133" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode133" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode134" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode134" />
        </ConductingEquipment>
		<ConductingEquipment name="T3EQS2" type="DIS" sxy:x="1" sxy:y="12">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode134" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode134" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode135" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode135" />
        </ConductingEquipment>
		<ConductingEquipment name="T3EQ2" type="CBR" sxy:x="1" sxy:y="14">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode135" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode135" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode136" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode136" />
        </ConductingEquipment>
		<ConductingEquipment name="T3EQS1" type="DIS" sxy:x="1" sxy:y="16">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode136" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode136" />
		  <Terminal name="terminal2" connectivityNode="substation1/voltageLevel2/bay13/connvtyNode96" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay13" cNodeName="connvtyNode96" />
        </ConductingEquipment>
		<ConductingEquipment name="W1EQSG11" type="DIS" sxy:x="2" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode129" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode129" />
        </ConductingEquipment>
		<ConductingEquipment name="W1EQSG21" type="DIS" sxy:x="2" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode130" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode130" />
        </ConductingEquipment>
		<ConductingEquipment name="W1T3EQSG1" type="DIS" sxy:x="2" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode132" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode132" />
        </ConductingEquipment>
		<ConductingEquipment name="W1T3EQSG2" type="DIS" sxy:x="2" sxy:y="10">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode133" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode133" />
        </ConductingEquipment>
		<ConductingEquipment name="T3EQSG22" type="DIS" sxy:x="2" sxy:y="11">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode134" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode134" />
        </ConductingEquipment>
		<ConductingEquipment name="T3EQSG21" type="DIS" sxy:x="2" sxy:y="13">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode135" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode135" />
        </ConductingEquipment>
		<ConductingEquipment name="T3EQSG11" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode136" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode136" />
        </ConductingEquipment>
		<ConductingEquipment name="W1EQSG22" type="DIS" sxy:x="2" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode131" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode131" />
        </ConductingEquipment>
		<ConductingEquipment name="W1E" type="IFL" sxy:x="3" sxy:y="5">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay18/connvtyNode131" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay18" cNodeName="connvtyNode131" />
        </ConductingEquipment>
		<ConductingEquipment name="K1EQSG1" type="DIS" sxy:x="2" sxy:y="0">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay12/connvtyNode95" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay12" cNodeName="connvtyNode95" />
        </ConductingEquipment>
		<ConductingEquipment name="K2EQSG1" type="DIS" sxy:x="2" sxy:y="15">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel2/bay13/connvtyNode96" substationName="substation1" voltageLevelName="voltageLevel2" bayName="bay13" cNodeName="connvtyNode96" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode129" pathName="substation1/voltageLevel2/bay18/connvtyNode129" sxy:x="2" sxy:y="2" />
		<ConnectivityNode name="connvtyNode130" pathName="substation1/voltageLevel2/bay18/connvtyNode130" sxy:x="2" sxy:y="4" />
		<ConnectivityNode name="connvtyNode131" pathName="substation1/voltageLevel2/bay18/connvtyNode131" sxy:x="1" sxy:y="6" />
		<ConnectivityNode name="connvtyNode132" pathName="substation1/voltageLevel2/bay18/connvtyNode132" sxy:x="1" sxy:y="8" />
		<ConnectivityNode name="connvtyNode133" pathName="substation1/voltageLevel2/bay18/connvtyNode133" sxy:x="2" sxy:y="10" />
		<ConnectivityNode name="connvtyNode134" pathName="substation1/voltageLevel2/bay18/connvtyNode134" sxy:x="1" sxy:y="11" />
		<ConnectivityNode name="connvtyNode135" pathName="substation1/voltageLevel2/bay18/connvtyNode135" sxy:x="2" sxy:y="13" />
		<ConnectivityNode name="connvtyNode136" pathName="substation1/voltageLevel2/bay18/connvtyNode136" sxy:x="2" sxy:y="15" />
      </Bay>
    </VoltageLevel>
	<VoltageLevel name="voltageLevel5" sxy:x="27" sxy:y="31">
      <Voltage unit="V">20</Voltage>
      <Bay name="bay1" sxy:x="1" sxy:y="1">
		<ConductingEquipment name="T1KQSG2" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay1/connvtyNode137" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay1" cNodeName="connvtyNode137" />
        </ConductingEquipment>
		<ConductingEquipment name="T1KQ2" type="DIS" sxy:x="0" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay1/connvtyNode137" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay1" cNodeName="connvtyNode137" />
          <Terminal name="terminal2" connectivityNode="substation1/voltageLevel5/bay1/connvtyNode138" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay1" cNodeName="connvtyNode138" />
        </ConductingEquipment>
		<ConductingEquipment name="conEquipIFL1" type="IFL" sxy:x="0" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay1/connvtyNode138" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay1" cNodeName="connvtyNode138" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode137" pathName="substation1/voltageLevel2/bay1/connvtyNode137" sxy:x="1" sxy:y="2" />
		<ConnectivityNode name="connvtyNode138" pathName="substation1/voltageLevel2/bay1/connvtyNode138" sxy:x="0" sxy:y="1" />
      </Bay>
      <Bay name="bay2" sxy:x="10" sxy:y="0">
		<ConductingEquipment name="T2KQSG1" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay2/connvtyNode139" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay2" cNodeName="connvtyNode139" />
        </ConductingEquipment>
		<ConductingEquipment name="T2KQ1" type="DIS" sxy:x="0" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay2/connvtyNode139" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay2" cNodeName="connvtyNode139" />
          <Terminal name="terminal2" connectivityNode="substation1/voltageLevel5/bay2/connvtyNode140" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay2" cNodeName="connvtyNode140" />
        </ConductingEquipment>
		<ConductingEquipment name="conEquipIFL1" type="IFL" sxy:x="1" sxy:y="2">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay2/connvtyNode140" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay2" cNodeName="connvtyNode140" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode139" pathName="substation1/voltageLevel2/bay2/connvtyNode139" sxy:x="1" sxy:y="2" />
		<ConnectivityNode name="connvtyNode140" pathName="substation1/voltageLevel2/bay2/connvtyNode140" sxy:x="1" sxy:y="2" />
      </Bay>
      <Bay name="bay3" sxy:x="6" sxy:y="7">
		<ConductingEquipment name="T2KQSG2" type="DIS" sxy:x="2" sxy:y="7">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay3/connvtyNode141" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay3" cNodeName="connvtyNode141" />
        </ConductingEquipment>
		<ConductingEquipment name="T2KQ2" type="DIS" sxy:x="1" sxy:y="1">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay3/connvtyNode141" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay3" cNodeName="connvtyNode141" />
          <Terminal name="terminal2" connectivityNode="substation1/voltageLevel5/bay3/connvtyNode142" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay3" cNodeName="connvtyNode142" />
        </ConductingEquipment>
		<ConductingEquipment name="conEquipIFL1" type="IFL" sxy:x="1" sxy:y="3">
          <Terminal name="terminal1" connectivityNode="substation1/voltageLevel5/bay3/connvtyNode142" substationName="substation1" voltageLevelName="voltageLevel5" bayName="bay3" cNodeName="connvtyNode142" />
        </ConductingEquipment>
		<ConnectivityNode name="connvtyNode141" pathName="substation1/voltageLevel2/bay3/connvtyNode141" sxy:x="1" sxy:y="1" />
		<ConnectivityNode name="connvtyNode142" pathName="substation1/voltageLevel2/bay3/connvtyNode142" sxy:x="1" sxy:y="2" />
      </Bay>
    </VoltageLevel>
  </Substation>
</SCL>
